package com.vlatkogalev.domain.coin.model

data class CoinCatalogCandidate(
    val externalReference: ExternalCoinReference,
    val title: String?,
    val countryOrIssuer: String?,
    val denomination: String?,
    val yearStart: Int?,
    val yearEnd: Int?,
    val composition: String? = null,
    val weightGrams: Double? = null,
    val diameterMm: Double? = null,
    val obverseDescription: String? = null,
    val reverseDescription: String? = null,
    val historicalContext: String? = null,
    val thumbnailUrl: String? = null,
    val numistaUrl: String? = null,
    val obverseLettering: String? = null,
    val reverseLettering: String? = null,
    val designers: List<String> = emptyList(),
    val thicknessMm: Double? = null,
    val shape: String? = null,
    val technique: String? = null,
    val orientation: String? = null,
    val edgeDescription: String? = null,
    val obverseDesigners: List<String> = emptyList(),
    val reverseDesigners: List<String> = emptyList(),
    val obversePictureUrl: String? = null,
    val reversePictureUrl: String? = null,
    val reverseThumbnailUrl: String? = null,
    val objectType: String? = null,
    val demonetized: Boolean? = null,
    val ruler: String? = null,
    val mintName: String? = null,
    val tags: List<String> = emptyList(),
    val catalogReferences: List<CatalogueNumber> = emptyList(),
)
