package com.vlatkogalev.domain.coin.model

object CountryAliasMapping {
    private val aliases: Map<String, String> = mapOf(
        "usa" to "united states",
        "us" to "united states",
        "united states of america" to "united states",
        "uk" to "united kingdom",
        "great britain" to "united kingdom",
        "england" to "united kingdom",
        "deutschland" to "germany",
        "bundesrepublik deutschland" to "germany",
        "france" to "france",
        "republique francaise" to "france",
        "rf" to "france",
        "italia" to "italy",
        "repubblica italiana" to "italy",
        "espana" to "spain",
        "reino de espana" to "spain",
        "nederland" to "netherlands",
        "the netherlands" to "netherlands",
        "nederlanden" to "netherlands",
        "belgie" to "belgium",
        "belgique" to "belgium",
        "belgien" to "belgium",
        "schweiz" to "switzerland",
        "suisse" to "switzerland",
        "svizzera" to "switzerland",
        "confoederatio helvetica" to "switzerland",
        "osterreich" to "austria",
        "canada" to "canada",
        "australia" to "australia",
        "new zealand" to "new zealand",
        "nz" to "new zealand",
        "japan" to "japan",
        "nippon" to "japan",
        "china" to "china",
        "people's republic of china" to "china",
        "prc" to "china",
        "russia" to "russia",
        "russian federation" to "russia",
        "rossiya" to "russia",
        "brazil" to "brazil",
        "brasil" to "brazil",
        "mexico" to "mexico",
        "estados unidos mexicanos" to "mexico",
        "south africa" to "south africa",
        "rsa" to "south africa",
        "suid-afrika" to "south africa",
        "india" to "india",
        "bharat" to "india",
        "greece" to "greece",
        "hellas" to "greece",
        "hellenic republic" to "greece",
        "ελλαδα" to "greece",
        "türkiye" to "turkey",
        "turkey" to "turkey",
        "turkiye" to "turkey",
        "polska" to "poland",
        "poland" to "poland",
        "ceska republika" to "czech republic",
        "czech republic" to "czech republic",
        "czechia" to "czech republic",
        "magyarorszag" to "hungary",
        "hungary" to "hungary",
        "sverige" to "sweden",
        "sweden" to "sweden",
        "norge" to "norway",
        "norway" to "norway",
        "danmark" to "denmark",
        "denmark" to "denmark",
        "suomi" to "finland",
        "finland" to "finland",
        "portugal" to "portugal",
        "eire" to "ireland",
        "ireland" to "ireland",
        "romania" to "romania",
        "romania" to "romania",
        "bulgaria" to "bulgaria",
        "balgariya" to "bulgaria",
    )

    fun normalize(raw: String?): String? {
        if (raw == null) return null
        val cleaned = raw.trim().lowercase()
        return aliases[cleaned] ?: cleaned
    }
}
