package com.vlatkogalev.domain.coin.model

object DenominationAliasMapping {
    private val aliases: Map<String, String> = mapOf(
        "1 cent" to "1 cent",
        "one cent" to "1 cent",
        "2 cent" to "2 cent",
        "two cents" to "2 cent",
        "5 cent" to "5 cent",
        "five cents" to "5 cent",
        "10 cent" to "10 cent",
        "ten cents" to "10 cent",
        "dime" to "10 cent",
        "one dime" to "10 cent",
        "20 cent" to "20 cent",
        "twenty cents" to "20 cent",
        "25 cent" to "25 cent",
        "quarter" to "25 cent",
        "quarter dollar" to "25 cent",
        "50 cent" to "50 cent",
        "fifty cents" to "50 cent",
        "half dollar" to "50 cent",
        "1 dollar" to "1 dollar",
        "one dollar" to "1 dollar",
        "$1" to "1 dollar",
        "2 dollar" to "2 dollar",
        "two dollars" to "2 dollar",
        "$2" to "2 dollar",
        "5 dollar" to "5 dollar",
        "five dollars" to "5 dollar",
        "10 dollar" to "10 dollar",
        "ten dollars" to "10 dollar",
        "20 dollar" to "20 dollar",
        "twenty dollars" to "20 dollar",
        "1 penny" to "1 penny",
        "one penny" to "1 penny",
        "2 pence" to "2 pence",
        "two pence" to "2 pence",
        "5 pence" to "5 pence",
        "five pence" to "5 pence",
        "10 pence" to "10 pence",
        "ten pence" to "10 pence",
        "20 pence" to "20 pence",
        "twenty pence" to "20 pence",
        "50 pence" to "50 pence",
        "fifty pence" to "50 pence",
        "1 pound" to "1 pound",
        "one pound" to "1 pound",
        "2 pound" to "2 pound",
        "two pounds" to "2 pound",
        "1 euro" to "1 euro",
        "one euro" to "1 euro",
        "2 euro" to "2 euro",
        "two euros" to "2 euro",
        "1 euro cent" to "1 euro cent",
        "one euro cent" to "1 euro cent",
        "2 euro cent" to "2 euro cent",
        "two euro cents" to "2 euro cent",
        "5 euro cent" to "5 euro cent",
        "five euro cents" to "5 euro cent",
        "10 euro cent" to "10 euro cent",
        "ten euro cents" to "10 euro cent",
        "20 euro cent" to "20 euro cent",
        "twenty euro cents" to "20 euro cent",
        "50 euro cent" to "50 euro cent",
        "fifty euro cents" to "50 euro cent",
        "1 franc" to "1 franc",
        "one franc" to "1 franc",
        "2 franc" to "2 franc",
        "two francs" to "2 franc",
        "5 franc" to "5 franc",
        "five francs" to "5 franc",
        "1 mark" to "1 mark",
        "one mark" to "1 mark",
        "2 mark" to "2 mark",
        "5 mark" to "5 mark",
        "1 yen" to "1 yen",
        "5 yen" to "5 yen",
        "10 yen" to "10 yen",
        "50 yen" to "50 yen",
        "100 yen" to "100 yen",
        "500 yen" to "500 yen",
        "1 yuan" to "1 yuan",
        "1 jiao" to "1 jiao",
        "1 rupee" to "1 rupee",
        "one rupee" to "1 rupee",
        "2 rupee" to "2 rupee",
        "5 rupee" to "5 rupee",
        "10 rupee" to "10 rupee",
        "1 peso" to "1 peso",
        "one peso" to "1 peso",
        "5 peso" to "5 peso",
        "10 peso" to "10 peso",
        "1 real" to "1 real",
        "5 centavos" to "5 centavos",
        "10 centavos" to "10 centavos",
        "25 centavos" to "25 centavos",
        "50 centavos" to "50 centavos",
        "1 kuna" to "1 kuna",
        "2 kuna" to "2 kuna",
        "5 kuna" to "5 kuna",
        "1 lira" to "1 lira",
        "1 ruble" to "1 ruble",
        "1 rouble" to "1 ruble",
        "2 ruble" to "2 ruble",
        "5 ruble" to "5 ruble",
        "10 ruble" to "10 ruble",
    )

    fun normalize(raw: String?): String? {
        if (raw == null) return null
        val cleaned = raw.trim().lowercase()
        return aliases[cleaned] ?: cleaned
    }
}
